version: "3"
services:
  app:
    container_name: app
    build: ./app
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./app:/usr/src/app
    stdin_open: true
    tty: true
    command: /bin/sh

  postgres:
    container_name: postgres
    build: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data:z
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
      LANG: ja_JP.UTF-8